### ISSUE TITLE
How to change Default Country when entering mobile number for sms Authentication 

### ISSUE THREAD

**Issue by Abhi150688** [twitter/digits-android#11]
By default United States (Country Code +1) gets loaded as the first value in the Country spinner list. How do I change this in such a way that the default country is the country in which the app is being used. 

So if a user logs in from India, the default country becomes India.

**Comment by efrohnhoefer** [comment]
Hi @Abhi150688, Thankyou for the feedback. We actually attempt to read the 2 digits ISO country code from the SIM card first. If unavailable we then default to "United States +1".

**Comment by Abhi150688** [comment]
Is there a way I can override the default. Currently we are planning to
deploy the app only in India so I would want to make the default to India.

On Monday, July 6, 2015, Eric Frohnhoefer <notifications@github.com> wrote:

> Hi @Abhi150688 <https://github.com/Abhi150688>, Thankyou for the
> feedback. We actually attempt to read the 2 digits ISO country code from
> the SIM card first. If unavailable we then default to "United States +1".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/digits-android/issues/11#issuecomment-118884366>
> .
>


-- 
*Website: www.nexchanges.io <http://nexchanges.io>*
*Regards,*
*Abhishek Malhotra*
*Mobile: 996 730 7197 *
*Nexchanges Marketplace Pvt. Ltd.*
*Follow Us on:  **Facebook
<https://www.facebook.com/nexchanges?ref_type=bookmark> || **Twitter*
<https://twitter.com/Nexchanges>

**Comment by dustedrob** [comment]
@Abhi150688 From a quick look a the source code, you could modify the init method from CountryListSpinner.java

**Comment by rallat** [comment]
Thanks for the feedback.
I think it makes sense from a product perspective, to add a config parameter to set the default country code for the app developer.
I'll add this to the product backlog.

**Comment by rallat** [comment]
@Abhi150688 this case is currently supported by using Digits.authenticate(autCallback,"+34") where 34 is the country code you want to use as the default. You need to append "+" at the beginning or it won't work. Thanks
