### ISSUE TITLE
How can i pass the mobile number automatically, instead of the user having to enter it manually? 

### ISSUE THREAD

**Issue by Abhi150688** [twitter/digits-android#15]
Query 1: 
Hi, I have written a piece of code that picks up the users mobile number automatically. The idea is to save the user the trouble of having to manually enter his number for the sms otp validation. 

Which class in your library should I make this change to? 

Query 2:
When the OTP sms arrives my app has the permission to read the incoming sms content and the otp code gets picked up automatically by the user without having to enter it manually. Now the sms otp is a 6 digit code. I want the submit OTP button below to get triggered automatically (without the user having to click on it) the moment the 6 digit code is available on the screen. How can i achieve this?

**Comment by efrohnhoefer** [comment]
Hi @Abhi150688 

1) We already support reading the phone number automatically. See [prefill the user's phone number](http://docs.fabric.io/android/digits/digits.html#prefill-the-user-s-phone-number). If something isn't currently working feel free to submit a PR or create an issue.

2) This isn't a feature we are looking to support. By clicking the user is accepting a Terms of Service.

**Comment by Abhi150688** [comment]
regarding pont 1: Isn't the user already agreeing to the terms of your service by providing a phone number in the first screen when he clicks the submit button which triggers the sms otp from your servers. I am talking about the next logical screen where the otp sms has arrived and I can just call the function behind the submit code button click when the edit text field for the otp code is filled with a 6 digit number. 


Regarding point 2: In my case, digits is not able to read the user's phone number. i am forced to enter the phone number manually every time. Can you point out where the relevant code is so that I can check why its not working.

**Comment by efrohnhoefer** [comment]
For user sign-up (the first time they use digits) we display a TOS on the confirmation screen too. I will bring this feedback to the team.

Relevant code can be found at:
[PhoneNumberUtils.java](https://github.com/twitter/digits-android/blob/master/digits/src/main/java/com/digits/sdk/android/PhoneNumberUtils.java)
[SimManager.java](https://github.com/twitter/digits-android/blob/master/digits/src/main/java/com/digits/sdk/android/SimManager.java)

It would be interesting to know the result of `TelephonyManager#getLine1Number()` for your device.

**Comment by rallat** [comment]
Hi Abhi,
You can pass the phone number to the Digits authentication flow by using this method: [Digits#authenticate(AuthCallback callback, String phoneNumber)](http://docs.fabric.io/javadocs/digits/1.6.2/)
Since the prefill feature is not working for your SIM. Do you mind to send us the result of this calls?
TelephonyManager#getLine1Number()
TelephonyManager#getSimCountryIso()
TelephonyManager#getNetworkCountryIso()
Please, send us this information to support@fabric.io
Thanks!

**Comment by Abhi150688** [comment]
Hi, any update on the first query here?

**Comment by efrohnhoefer** [comment]
Did you email support? With out knowing what your device returns it will be difficult to debug. Knowing the following values would help.

    TelephonyManager#getLine1Number()
    TelephonyManager#getSimCountryIso()
    TelephonyManager#getNetworkCountryIso()

Alternately you could post the code you wrote.

**Comment by Abhi150688** [comment]
Okay for me the TelephonyManager.getLine1Number() is returning null. Hence as a work around I am passing the number directly to Digits via the Digits#authenticate(AuthCallback callback, String phoneNumber) method. 

Can you tell me how can i pass the Country code also directly?

**Comment by Abhi150688** [comment]
and the other query being that once the SMS otp has been filled, can the submit code button be triggered automatically as the user has already agreed to your terms and conditions in the previous screen when clicking on "Send Confirmation code"

**Comment by efrohnhoefer** [comment]
We have currently have no plan to enable auto submit.

You set the country code by appending it to the phone number (i.e. +15555051234). If `TelephonyManager#getLine1Number()` is null how are you getting the users number?

**Comment by Abhi150688** [comment]
Getting the user number from account manager. Vibers account name is the
users phone number

On Friday, August 7, 2015, Eric Frohnhoefer <notifications@github.com>
wrote:

> We have currently have no plan to enable auto submit.
>
> You set the country code by appending it to the phone number (i.e.
> +15555051234). If TelephonyManager#getLine1Number() is null how are you
> getting the users number?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twitter/digits-android/issues/15#issuecomment-128554166>
> .
>


-- 
*Website: www.nexchanges.io <http://nexchanges.io>*
*Regards,*
*Abhishek Malhotra*
*Mobile: 996 730 7197 *
*Nexchanges Marketplace Pvt. Ltd.*
*Follow Us on:  **Facebook
<https://www.facebook.com/nexchanges?ref_type=bookmark> || **Twitter*
<https://twitter.com/Nexchanges>

**Comment by Abhi150688** [comment]
Obviously it only covers for cases where the user has Viber installed

On Friday, August 7, 2015, Abhishek Malhotra <abhishek@nexchanges.com>
wrote:

> Getting the user number from account manager. Vibers account name is the
> users phone number
>
> On Friday, August 7, 2015, Eric Frohnhoefer <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> We have currently have no plan to enable auto submit.
>>
>> You set the country code by appending it to the phone number (i.e.
>> +15555051234). If TelephonyManager#getLine1Number() is null how are you
>> getting the users number?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/twitter/digits-android/issues/15#issuecomment-128554166>
>> .
>>
>
>
> --
> *Website: www.nexchanges.io <http://nexchanges.io>*
> *Regards,*
> *Abhishek Malhotra*
> *Mobile: 996 730 7197 *
> *Nexchanges Marketplace Pvt. Ltd.*
> *Follow Us on:  **Facebook
> <https://www.facebook.com/nexchanges?ref_type=bookmark> || **Twitter*
> <https://twitter.com/Nexchanges>
>
>

-- 
*Website: www.nexchanges.io <http://nexchanges.io>*
*Regards,*
*Abhishek Malhotra*
*Mobile: 996 730 7197 *
*Nexchanges Marketplace Pvt. Ltd.*
*Follow Us on:  **Facebook
<https://www.facebook.com/nexchanges?ref_type=bookmark> || **Twitter*
<https://twitter.com/Nexchanges>

**Comment by efrohnhoefer** [comment]
If you just want to set the country code to India you can pass "+91" to `Digits#authenticate()`. For example:

    Digits.authenticate(callback, "+91");

Note: we do set the default country code using `TelephonyManager#getSimCountryIso()` or `TelephonyManager#getNetworkCountryIso()` if available.

**Comment by efrohnhoefer** [comment]
I think in the future we will look to improve the API for setting a default country code.

**Comment by lokendrakushwah** [comment]
Hi, One of my users is facing a strange issue with Twitter Digit OTP verification. After entering his mobile number and clicking on 'Send OTP" he is taken to next screen to enter OTP verification code. However as the SMS with OTP reaches to his mobile...Digits screen automatically changes and user again sees screen to enter mobile number. That means it is going to previous screen. 

Do you have any input for this issue?

Thanks
Lokendra Kushwah

**Comment by ashwinraghav** [comment]
Thanks for reaching out. What version of Digits are you using? Could we also get the device and OS specs
