### ISSUE TITLE
launch digits flow from textField

### ISSUE THREAD

**Issue by prazjain** [twitter/digits-android#16]
Hi,
Your blog says you have implemented this feature in June release : http://get.digits.com/blog/digits-june-update

But I cannot find any examples of how this can be actually achieved.
Can you please tell how we can launch digits flow from textField.

Thanks

**Comment by rallat** [comment]
Hi prazjain,
You can pass the phone number as a parameter to the method Digits.authenticate(). Check the javadocs:
http://docs.fabric.io/javadocs/digits/1.7.0/com/digits/sdk/android/Digits.html#authenticate(com.digits.sdk.android.AuthCallback, java.lang.String)
Thanks
