### ISSUE TITLE
Unable to resume CodeActivity when re-launching app from launcher

### ISSUE THREAD

**Issue by emhagman** [twitter/digits-android#18]
I understand that users can use the recent app switcher to change between activities to type in their code after receiving it via text. However, what about when users decide to tap the app icon again to go back to the launcher?

Currently, as far as I can tell, the only way to get back to the "Enter Code" screen is through the app switcher.

Is there a way to bring the CodeActivity back to the front using something like `mDigitsCallbackManager.onResume(this)` we can put in our on `onResume()`?

**Comment by rallat** [comment]
Thank you for your feedback, We really appreciate it.
The Digits auth flow can't be started on the "EnterCode" screen, because confirmation codes expire. Moreover we are working on new features that won't work in that case.

**Comment by emhagman** [comment]
I understand codes expire but I am talking about the case where someone is trying to enter the code within seconds of getting it. Currently, it doesn't appear that there is a way to bring the user back to the "Confirm Code" screen if they decide to open their SMS app to read the code and then click on our app's launcher icon instead of using the app switcher in Android to back to the "Confirm Code" screen.

Maybe I am implementing the Digits.authenticate() call wrong but it appears this is the case.
