### ISSUE TITLE
Crash when user click "sign in" twice

### ISSUE THREAD

**Issue by cuiyuming** [twitter/digits-android#2]

**Comment by rallat** [comment]
I wasn't able to reproduce it. Can you give me a little bit more of context how you get the crash? Can you send over the logcat?

**Comment by cuiyuming** [comment]
Hi Isreal,

My phone is Nexus 6 and the os is android 5.1, but I think it is the os,
one of my friends has nexus 5 with android 5.0, and he also get the crash.


Here is the logcat message when it crashes:



java.lang.NullPointerException: Attempt to read from field
'com.android.server.am.TaskRecord
com.android.server.am.ActivityRecord.task' on a null object reference
            at android.os.Parcel.readException(Parcel.java:1552)
            at android.os.Parcel.readException(Parcel.java:1499)
            at
android.app.ActivityManagerProxy.finishActivityAffinity(ActivityManagerNative.java:2718)
            at android.app.Activity.finishAffinity(Activity.java:4685)
            at
io.fabric.sdk.android.services.common.CommonUtils.finishAffinity(CommonUtils.java:954)
            at
com.digits.sdk.android.DigitsControllerImpl$1.run(DigitsControllerImpl.java:142)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Best regards
Yuming

Here is the screen shot:

**Comment by efrohnhoefer** [comment]
Hi @cuiyuming, 

While attempting to reproduce we noticed multiple clicks would launch multiple activities. We have now disabled clicks while showing the progress state. This should prevent multiple clicks. This fix will be included in the next release.

**Comment by cuiyuming** [comment]
Thank you so much for your prompt reply, and we are looking forward to the
new release.

**Comment by rallat** [comment]
It will be fix for next release.
Thank you for reporting it!

**Comment by cuiyuming** [comment]
We are still waiting the fix in our project, do you have a plan?

**Comment by efrohnhoefer** [comment]
@cuiyuming This issue has been resolved and released. You just need to update you digits version. See: https://github.com/twitter/digits-android/commit/f937f2a85584cc79b9f16f5befc42b652234a7c5
