### ISSUE TITLE
Configure number of digits in OTP

### ISSUE THREAD

**Issue by 0jickson0** [twitter/digits-android#21]
Hi , 

Currently we are getting 6 digit number as OTP. Is it possible to configure it to 4 digits OTP?

Thanks,
Jickson

**Comment by rallat** [comment]
Unfortunately is not configurable. I am curious, why is the reason to configure the OTP to use less digits?
Thanks

**Comment by 0jickson0** [comment]
Thanks for the update.

It is difficult to remember 6 digits code for a normal user while using Call to get the OTP. It would be easy to remember and enter OTP if its only 4 digits.
