### ISSUE TITLE
Prevent user from entering OTP from other phone

### ISSUE THREAD

**Issue by 0jickson0** [twitter/digits-android#22]
Hi,

Query:
How can we prevent users from getting OTP from other phone number?

One option is to auto fill the phone number field and disable edit. But its not possible to auto fill all phone numbers(dependent on phone carrier), we may not be able to use this.

Currently we are able to auto fill OTP by reading SMS. So if we disable the editing in OTP field, then user will not be able to enter OTP of other phone. 

Can we disable the OTP edittext field?

Thanks,
Jickson P

**Comment by efrohnhoefer** [comment]
Hi @0jickson0 I am trying to understand you use case. What is the reason for not allowing a user to enter the OTP from another device? What if users wants to log into your app from a tablet without call or sms? What if users have multiple numbers (or devices) but always want to login with the same number?

Currently Digits doesn't support disabling the EditText field.
