### ISSUE TITLE
HTTP Error: 401 Authorization Required, API Error: 245, User Message: Try Again

### ISSUE THREAD

**Issue by 0jickson0** [twitter/digits-android#23]
Hi ,

When a user is requesting for OTP, It will show "Try again" as error sometimes. When I checked the log it is showing "HTTP Error: 401 Authorization Required, API Error: 245, User Message: Try Again".

Most of the time OTP works fine, but sometimes this error is shown. How can we resolve this issue?

**Comment by rallat** [comment]
Hey Thanks for reporting this. 
Can you fill the form? Support will contact you
https://docs.google.com/forms/d/1dDMpmgfOuCRvEHlXfnsylF4MIrDgIMm3dSrndGEhrFo/viewform
