### ISSUE TITLE
Crash from Digits activities, when we are using only twitter-kit.

### ISSUE THREAD

**Issue by alexkipar** [twitter/digits-android#24]
We are using only twitter-kit (1.7.2 in the latest build) in our application, but from time to time we see crashes with the stacktrace example's below. It usually happens soon after upload to the google play, but it could also happen later. We guess that it happens due to some google play inner monkey tests, due to the strange device info (model - "Full Android on Emulator") and anonymous user.

> java.lang.IllegalAccessError: This activity can only be started from Digits
> at com.digits.sdk.android.DigitsActionBarActivity.onCreate(DigitsActionBarActivity.java:28)
> at android.app.Activity.performCreate(Activity.java:5187)
> at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2065)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2146)
> at android.app.ActivityThread.access$600(ActivityThread.java:131)
>at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
>at android.os.Handler.dispatchMessage(Handler.java:99)
>at android.os.Looper.loop(Looper.java:137)
>at android.app.ActivityThread.main(ActivityThread.java:4831)
>at java.lang.reflect.Method.invokeNative(Native Method)
>at java.lang.reflect.Method.invoke(Method.java:535)
>at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
>at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>at dalvik.system.NativeStart.main(Native Method)

or

>java.lang.IllegalAccessError: This activity can only be started from Digits
>at com.digits.sdk.android.bs.a(Unknown Source)
>at com.digits.sdk.android.FailureActionBarActivity.onCreate(Unknown Source)
>at android.app.Activity.performCreate(Activity.java:5187)
>at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
>at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
>at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2145)
>at android.app.ActivityThread.access$600(ActivityThread.java:130)
>at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1211)
>at android.os.Handler.dispatchMessage(Handler.java:99)
>at android.os.Looper.loop(Looper.java:137)
>at android.app.ActivityThread.main(ActivityThread.java:4847)
>at java.lang.reflect.Method.invokeNative(Native Method)
>at java.lang.reflect.Method.invoke(Method.java:535)
>at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
>at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>at dalvik.system.NativeStart.main(Native Method)

**Comment by efrohnhoefer** [comment]
Hi @alexkipar, TwitterKit also includes Digits. If you like you can only include on twitter-core and/or tweet-ui. We have noticed the same crashes and also believe this is related to automatic test by Google or other third-parties.
