### ISSUE TITLE
digits and fabric with Android Studio 1.4 Beta

### ISSUE THREAD

**Issue by dmwest2008** [twitter/digits-android#25]
I'm using the Android Studio 1.4 beta builds (I find it much better for ndk project builds).

I cannot get the Digits or Fabric plugin to work with Android Studio 1.4. The gradle build systems are different.  Android Studio 1.3 uses apply plugin: 'com.android.application'  1.4 uses apply plugin: 'com.android.model.application'. Your plugin requires com.android.application. When I use com.android.model. application for Android Studio 1.4, the build fails. 

For example your instructions:
apply plugin: 'com.android.application'
//Put Fabric plugin after Android plugin
apply plugin: 'io.fabric'

But that first line in a 1.4 build is apply plugin: 'com.android.model.application'

Is there any way to get digits and fabric working with Android Studio 1.4?  Thanks

**Comment by BaJIuK** [comment]
I faced with same problem. Looking forward to solve this.

**Comment by manishpatelgt** [comment]
Faced the same issue. but the same code worked in Studio 1.2.

**Comment by BaJIuK** [comment]
It's better to user stable gradle plugin with custom mk-files.
