### ISSUE TITLE
OkHttp 2.5.0 and Digits 1.8.0

### ISSUE THREAD

**Issue by skhaz** [twitter/digits-android#27]
Hi,
Recently I've upgraded OkHttp to version 2.5.0 and Digits to 1.8.0 and I got this error `"HTTP Error: 403 , API Error: 239, User Message: Try Again"`.

The only way to solve this is downgrade the version to 2.3.0 of OkHttp?

**Comment by kairon007** [comment]
+1

**Comment by dnalves** [comment]
+1

**Comment by caioquinto** [comment]
+1

**Comment by thomasdsouza** [comment]
+1

**Comment by farukcankaya** [comment]
+1

**Comment by messer00** [comment]
+1

**Comment by efrohnhoefer** [comment]
This issue was resolved. See [changelog](https://docs.fabric.io/android/changelog.html) for more details.
