### ISSUE TITLE
Typo on Number Input activity

### ISSUE THREAD

**Issue by danmademe** [twitter/digits-android#3]
As you can see here there is a formatting error on the double quote 

-By tapping" Send confirmation code" above, 

should be 

-By tapping "Send confirmation code" above,

![screenshot_2015-06-17-10-43-32](https://cloud.githubusercontent.com/assets/399473/8202849/dd5d4722-14dd-11e5-81ed-cb0d73219dd1.png)

**Comment by rallat** [comment]
Thank you for reporting this @danmademe. I'll fix it for the next release

**Comment by rallat** [comment]
@danmademe By the way, what version of digits are you using? Thanks

**Comment by rallat** [comment]
This should be fixed already in the last digits version
