### ISSUE TITLE
Digits 1.9.0 missing translation

### ISSUE THREAD

**Issue by njovy** [twitter/digits-android#30]
I updated Digits from 1.8.0 to 1.9.0 and noticed the string in the auth button doesn't show Korean text correctly. It didn't happen 1.8.0.

**Comment by DenisBronx** [comment]
Same here for the Italian text

**Comment by efrohnhoefer** [comment]
Thanks for the information. We are working on updating all the translations.

**Comment by jonauz** [comment]
I found same issue for Chinese Simplified. Using 1.12.0 version of Digits SDK.

**Comment by efrohnhoefer** [comment]
Most of the translations have been updated and will be released shorty.
