### ISSUE TITLE
Some times digits throws exception about network connection

### ISSUE THREAD

**Issue by mdenissov** [twitter/digits-android#34]
Some times digits throws exception about network connection, but in logcat I found next message:

 HTTP Error: No authentication challenges found, API Error: 0, User Message: Проверьте сеть и попробуйте ещё раз.

This message throws with several phone numbers, but with other work great!

**Comment by mdenissov** [comment]
Scenario:

Step 1. Device ONE  (with same phone number) input phone number: +77018079414 result: Please check your internet connection.
Step 2. Device TWO  (with other phone number) input phone number: +77018079414  result: Login successful !!!
Step 3. Device ONE (again) input number: +77018079414 result:  Login successful !! And now this phone number login well at any devices.

**Comment by dustedrob** [comment]
Yeah, i can confirm this is still an issue an i can reproduce it like @mdenissov  says. The problem is that it won't even let you go to the automatic voice call part.

**Comment by efrohnhoefer** [comment]
@mdenissov this message with api code 0 would indicate a hard network failure (ie DNS failure, timeout, address unreachable). This is an issue we can message better by logging the actual networking errors. 

@dustedrob without networking voice calling isn't going to help. Any help reproducing the issue would help.

Looking at the error codes there are four API errors that would cause this message to be displayed:
REGISTRATION_GENERAL_ERROR = 284
REGISTRATION_OPERATION_FAILED = 302
SPAMMER = 240
CLIENT_NOT_PRIVILEGED = 87

If you see any of these errors we may be able look back at our server logs.

**Comment by mdenissov** [comment]
@efrohnhoefer  When I sent phone number and retrieve message "Please check your internet connection.", I saw a request and a response in Findler. So I have yet one problem number and I will try reproduce and record all steps to show you.

**Comment by dustedrob** [comment]
@efrohnhoefer The problem is that the phone does have both internet connection and phone service. That's why it's so weird. I can reproduce this everytime with a chinese Jiayu phone with Android 4.2 no matter what SIM you put on it. Maybe it is a coincidence or maybe it is OS related?

**Comment by mdenissov** [comment]
Same problem with HTC Desire 500 dual sim.

**Comment by efrohnhoefer** [comment]
@mdenissov what is Findler? Note we use HTTPS with certificate pinning. Any thing sitting between app and servers could be causing security errors.

@dustedrob Maybe related to: https://github.com/square/okhttp/issues/1114. I will read thru the issue and see what can be done.

**Comment by mdenissov** [comment]
@efrohnhoefer I said about Findler because, I saw response from server (not readable, but it was) and it was not internet connection error, DNS error or something like this. 

User with phone number +77018079414 He could not send the phone number about 3 weeks, with Wi-Fi (with different internet providers) and 4G/LTE. But after scenario than I described before everything was working fine.

**Comment by mdenissov** [comment]
I use okhttp:2.5.0 with digits:1.9.0 may they conflict ?

**Comment by njovy** [comment]
@mdenissov Were you able to resolve this issue? I had the same problem and contacted Fabric support and didn't really help. All they said was "let the team know". It's been more than two months and I guess they decide to ignore my email or something.

**Comment by mdenissov** [comment]
In our project we have another problems with digits, like start activity at new task, phone activity doesn't close after successful login, SMS code doesn't received automatically. So we have wrote own realization with using SMS gateway.

**Comment by njovy** [comment]
@mdenissov Luckily, I didn't have to use NEW_TASK when my app launches an activity so I didn't see that problem. Let me know if you find a way to get an SMS code as I am having the exact same issue as you.
I used phone numbers provided by users whom couldn't get an SMS to see what is going on since they didn't do anything after I provided information they asked. I made a request using Galaxy Note 2 and it was able to make a request. An SMS was delivered to a user's device. However, the user got the error message "Try Again" when she tried to use her own number. This issue is there but Fabric support team didn't seem to care. I guess this issue isn't logged to their backend servers and they said everything looks normal.

**Comment by TKBurner** [comment]
@njovy If you want to reach out to support@fabric.io or on our forums at twittercommunity.com the Fabric support team would still love to help. Thanks! :)

**Comment by njovy** [comment]
@TKBurner You are the third person from Fabric support who I've talked to, and you've stopped sending messages back just as the other have. I have provided a list of phone numbers and carriers as you requested. However nothing has been changed after two months. The users still can't sign in, and most users have given up trying my app. In addition, the coverage for my app seems to be getting lower and lower, as I am getting more emails and 1 star review about how users can't request an authentication code as the number of daily installs grows.

I tried what you mentioned already, but it didn't help. I am here to see what other developers have done to solve this issue as well.

**Comment by guptavps** [comment]
My user is facing the same problem - "Check your network connection". Eample Phone number +919874709009. If i knew earlier that Digits has so many problems in receiving SMS code, i wpould not have opted for it....I am stuck, is there a workaround please..

**Comment by guptavps** [comment]
And i am using the latest 1.9.2 plugin version..

**Comment by efrohnhoefer** [comment]
Resolved see #44

**Comment by hero78** [comment]
Digits is failing to send sms on MTN mobile carrier based in Uganda . It's short code (+256)-{
078,077} .But the automated voice call works on that line.Could you be having a solution for that?.Thanks
