### ISSUE TITLE
Getting an HTTP Error on Android devices running Jelly Bean (SDK: 16)

### ISSUE THREAD

**Issue by njovy** [twitter/digits-android#44]
Digits: 1.9.1
OKHTTP: 2.5.0
Android SDK: 4.1.2
Logcat: HTTP Error: No authentication challenges found, API Error: 0, User Message: Please check your network and try again.

I noticed this issue was closed because the team had concluded that the issue happened as a result of a backend problem. However, I think it needs to be investigated more. If in fact this issue occurred due to backend servers, it doesn't make sense that devices are getting different results when they are connected to the same wireless network and using the same number. If this was a backend issue as the team said, a problematic number would have to fail on other devices as well, but the results vary on different android devices. This is why I think Digits SDK team should reinvestigate it. I have contacted Fabric support, but didn't make any progress. Please investigate this more, as developers see this issue constantly.

**Comment by efrohnhoefer** [comment]
At which screen to do get the error message (phone number entry, confirmation code entry, pin entry, or email entry)? What version of Retrofit are you using? Can you run `./gradlew dependencies` and share the results of the release variant? Should look something like:

```
release - Published Configuration for Variant release
+--- com.android.support:appcompat-v7:22.2.0
|    \--- com.android.support:support-v4:22.2.0
|         \--- com.android.support:support-annotations:22.2.0
+--- project :sdk:fabric:fabric
\--- project :sdk:twitter:twitter-core
     +--- com.squareup.retrofit:retrofit:1.8.0
     |    \--- com.google.code.gson:gson:2.3
     +--- com.google.code.gson:gson:2.2.4 -> 2.3
     \--- project :sdk:fabric:fabric
```

Also do you see [this error](https://github.com/square/retrofit/issues/854) anywhere in you logs? Look like somehow the oAuth token isn't being included in the HTTP headers.

**Comment by njovy** [comment]
1. At which screen to do get the error message (phone number entry, confirmation code entry, pin entry, or email entry)? 
Phone Number entry
2. What version of Retrofit are you using?
1.9.0
3. Can you run ./gradlew dependencies and share the results of the release variant? 
I've attached the results of the release variant.

```
+--- project :omedia
|    +--- project :ocommon
|    |    +--- com.android.support:support-annotations:+ -> 23.1.0
|    |    +--- io.reactivex:rxjava:1.0.15
|    |    +--- io.reactivex:rxandroid:1.0.1
|    |    |    \--- io.reactivex:rxjava:1.0.13 -> 1.0.15
|    |    +--- de.greenrobot:eventbus:2.4.0
|    |    \--- com.google.dagger:dagger:2.0.1
|    |         \--- javax.inject:javax.inject:1
|    \--- com.squareup.okhttp:okhttp:2.5.0
|         \--- com.squareup.okio:okio:1.6.0
+--- project :odesign
|    +--- com.android.support:design:23.1.0
|    |    +--- com.android.support:appcompat-v7:23.1.0
|    |    |    \--- com.android.support:support-v4:23.1.0
|    |    |         \--- com.android.support:support-annotations:23.1.0
|    |    +--- com.android.support:recyclerview-v7:23.1.0
|    |    |    +--- com.android.support:support-annotations:23.1.0
|    |    |    \--- com.android.support:support-v4:23.1.0 (*)
|    |    \--- com.android.support:support-v4:23.1.0 (*)
|    \--- project :ocommon (*)
+--- project :olocation
|    +--- com.google.android.gms:play-services-location:7.5.0
|    |    +--- com.google.android.gms:play-services-base:7.5.0
|    |    |    \--- com.android.support:support-v4:22.0.0 -> 23.1.0 (*)
|    |    \--- com.google.android.gms:play-services-maps:7.5.0
|    |         \--- com.google.android.gms:play-services-base:7.5.0 (*)
|    \--- project :ocommon (*)
+--- project :oinapp
+--- project :ortc
|    \--- project :ocommon (*)
+--- project :conceal
+--- com.android.support:appcompat-v7:23.1.0 (*)
+--- com.android.support:recyclerview-v7:23.1.0 (*)
+--- com.android.support:palette-v7:23.1.0
|    \--- com.android.support:support-v4:23.1.0 (*)
+--- com.android.support:cardview-v7:23.1.0
+--- com.android.support:percent:23.1.0
|    \--- com.android.support:support-v4:23.1.0 (*)
+--- com.google.android.gms:play-services-gcm:7.5.0
|    \--- com.google.android.gms:play-services-base:7.5.0 (*)
+--- com.google.dagger:dagger:2.0.1 (*)
+--- com.squareup.retrofit:retrofit:1.9.0
|    \--- com.google.code.gson:gson:2.3.1
+--- com.jakewharton:butterknife:7.0.1
+--- com.jakewharton.timber:timber:4.0.1
+--- com.jakewharton.byteunits:byteunits:0.9.0
+--- com.jakewharton.threetenabp:threetenabp:1.0.2
|    \--- org.threeten:threetenbp:1.3
+--- com.squareup.okhttp:okhttp-ws:2.5.0
|    \--- com.squareup.okhttp:okhttp:2.5.0 (*)
+--- org.parceler:parceler-api:1.0.3
+--- com.crashlytics.sdk.android:crashlytics:2.5.2
|    +--- com.crashlytics.sdk.android:answers:1.3.2
|    |    \--- io.fabric.sdk.android:fabric:1.3.6 -> 1.3.7
|    +--- io.fabric.sdk.android:fabric:1.3.6 -> 1.3.7
|    +--- com.crashlytics.sdk.android:crashlytics-core:2.3.5
|    |    +--- com.crashlytics.sdk.android:answers:1.3.2 (*)
|    |    \--- io.fabric.sdk.android:fabric:1.3.6 -> 1.3.7
|    \--- com.crashlytics.sdk.android:beta:1.1.3
+--- com.digits.sdk.android:digits:1.9.1
|    +--- com.twitter.sdk.android:twitter-core:1.6.1
|    |    +--- com.squareup.retrofit:retrofit:1.8.0 -> 1.9.0 (*)
|    |    +--- io.fabric.sdk.android:fabric:1.3.7
|    |    \--- com.google.code.gson:gson:2.2.4 -> 2.3.1
|    \--- io.fabric.sdk.android:fabric:1.3.7
\--- com.crashlytics.sdk.android:crashlytics-ndk:1.1.1
     +--- io.fabric.sdk.android:fabric:1.3.5 -> 1.3.7
     \--- com.crashlytics.sdk.android:crashlytics-core:2.3.4 -> 2.3.5 (*)

```

4. Also do you see this error anywhere in you logs? 
No, I don't see "java.lang.IllegalArgumentException: method POST must have a request body" when it shows the error message. I tested 5 different numbers on my android devices, but my Galaxy S2 couldn't make a request for 2 out of the 5 numbers. It was however, able to receive an SMS code for the 3 other numbers. Other devices(Note2, Nexus4, and Nexus5X) could all receive SMS codes from all numbers.

**Comment by njovy** [comment]
The error message has been changed to "E/Digits: HTTP Error: 401 Authorization Required, API Error: 32, User Message: 다시 시도" with the same number.

**Comment by njovy** [comment]
@efrohnhoefer  Any new updates on this?

**Comment by njovy** [comment]
All users whom have seen this issue are using Jelly Bean (4.1.x).

**Comment by BackPackerDz** [comment]
I have the same problem... any solution please ?

**Comment by dustedrob** [comment]
There have been many related issues posted here. I'd like to add that this problem is not related to the SDK level, as I've seen this on levels >16. I suspect that this is more of a backend problem on Twitter's side.

**Comment by njovy** [comment]
@dustedrob Do Digits auth servers check SDK version of clients? I reported this issue to fabric support about three months ago but they stopped sending me back for this issue. Where do I contact if this is a case?

**Comment by BackPackerDz** [comment]
That sounds strange, but If I log in to get.digits.com it works !

**Comment by njovy** [comment]
@dustedrob As @BackPackerDz pointed out, I was able to login digits.com/signin as well on a problematic phone running 4.1.2. This contradicts your statement since the issue only happens on a native android app.

**Comment by njovy** [comment]
@efrohnhoefer I have provided information you requested but I haven't heard back from you for a while. Is the issue not going to be fixed?

**Comment by guptavps** [comment]
I am having same problem on Android L. If i change the phone number, i am not able to get SMS and get an error 401 API error:32. Please help.

**Comment by MitchDart** [comment]
Hey guys, we having the same issue with Jelly Bean devices only. Is there any updated regarding this?

**Comment by efrohnhoefer** [comment]
Looks like I mistakenly believed that Digits was using OkHttp for preforming network requests. However, for Digits to use OkHttp one must include `okhttp-urlconnection` too. See: [DefaultClient.java#L70].(https://github.com/twitter/twitter-kit-android/blob/a9ff5134a736d10f70331ddea4db35c13cb86c89/twitter-core/src/main/java/com/twitter/sdk/android/core/DefaultClient.java#L70) Both `okhttp-urlconnection` and `okhttp` should be included as compile dependencies.

```groovy
compile com.squareup.okhttp:okhttp:2.7.3
compile com.squareup.okhttp:okhttp-urlconnection:2.7.3
```

Judging from various SO posts [here](http://stackoverflow.com/questions/11810447/httpurlconnection-worked-fine-in-android-2-x-but-not-in-4-1-no-authentication-c), [here](http://stackoverflow.com/questions/17121213/java-io-ioexception-no-authentication-challenges-found), and [here](http://stackoverflow.com/questions/14550131/http-basic-authentication-issue-on-android-jelly-bean-4-1-using-httpurlconnectio/14551482#14551482), `HttpURLConnection ` was broken on various versions of Android. Using OkHttp may alleviate this issue.

**Comment by efrohnhoefer** [comment]
I got reports that adding `okhttp-urlconnection` to dependency list resolved this issue with older devices.

Note: If including the Digits dependency directly and OkHttp version is >2.3 one should explicitly include latest version of `twitter-core` to work around #27.
```groovy
compile('com.digits.sdk.android:digits:1.9.3@aar') {
  transitive = true;
}
compile 'com.twitter.sdk.android:twitter-core:1.6.4'
compile 'com.squareup.okhttp:okhttp:2.7.3'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.3'
```

The Digits dependency on `twitter-core` will be updated in the next release. Hopefully in the next few days.

**Comment by njovy** [comment]
@efrohnhoefer Thanks for this fix! I will add ```okhttp-urlconnection``` to my gradle file.

**Comment by efrohnhoefer** [comment]
:+1:

**Comment by orignMaster** [comment]
I added `okhttp-urlconnectio` to my gradle file and the issue resolved. +1

**Comment by efrohnhoefer** [comment]
**Note:** Digits was updated to v1.9.4 yesterday. There should be no need to explicitly include latest version of `twitter-core`.

**Comment by jehad-suliman** [comment]
Using version 1.10.2 and adding 
    `com.squareup.okhttp:okhttp:2.7.3
    com.squareup.okhttp:okhttp-urlconnection:2.7.3`
put still not working
