### ISSUE TITLE
Setting predefined country code for some countries does not work

### ISSUE THREAD

**Issue by vualeks** [twitter/digits-android#45]
Hi,

I've tried "+382" and "+381" (Montenegro and Serbia) and it remains set to +1 (USA). When I tried with +34 or +43, it worked ok (Spain and Austria). Can you please check that?

**Comment by mikebonnell** [comment]
Since you posted on Twitter Community, we can discuss this issue there.

**Comment by efrohnhoefer** [comment]
Looks like there is an issue processing 3 digit country codes. This will be addressed in a future release.

**Comment by efrohnhoefer** [comment]
This issue has been resolved in version 1.9.3
