### ISSUE TITLE
Trouble implementing Digits SMS Authentication in a Hybrid App built using Ionic & Cordova

### ISSUE THREAD

**Issue by Abhi150688** [twitter/digits-android#50]
Hi,
I am building a hybrid app for Android & iOS using Ionic and I am using Digits for the SMS Authentication of users. Currently your system allows for only andorid & ios app sdk. How can i use it in a ionic based app?

**Comment by efrohnhoefer** [comment]
We don't currently support Ionic framework and we don't currently have any plans to support it. Since Iconic is a web framework have to experimented with our web login? You also might find more help at https://twittercommunity.com/c/fabric.
