### ISSUE TITLE
Not receiving confirmation email

### ISSUE THREAD

**Issue by shahimclt** [twitter/digits-android#52]
I enable email collection in my app. It is asking for email but no email verification link is sent to the email address. Is there any prerequisites for that.

PS: I am currently in debug build, not yet published to store.

**Comment by mikebonnell** [comment]
Hey @shahimclt,

For any questions around how to use Digits or around not getting data, such as email, that you expect, please raise those on [TwitterCommunity.com/c/fabric] (url) and we'll take a look. Thanks!

-Mike
