### ISSUE TITLE
Buttons with long text are displayed incorrectly.

### ISSUE THREAD

**Issue by mxl** [twitter/digits-android#54]
![screenshot_20160305-183037](https://cloud.githubusercontent.com/assets/1078685/13548400/884f9720-e300-11e5-8d76-46588ecf271d.png)

**Comment by mikebonnell** [comment]
Can you share more details about which specific languages you're seeing this on and which version of Android you're running, and the device?

**Comment by mxl** [comment]
@mikebonnell Russian language. Android 6.0.1. Nexus 5.

I think that there are 2 ways to solve this issue:
1. Make buttons full width.
2. Remove border and center button title.

Also I think it would be better if counter on third button was part of button title and was placed in parentheses.

**Comment by mikebonnell** [comment]
Perfect, thanks. I'm going to close this and track internally.

**Comment by mxl** [comment]
@mikebonnell Also on Android 4.1.1 (Genymotion emulator) button backgrounds have black color. I think this is also true for all pre-lollipop Android version.

![device-2016-03-16-160649](https://cloud.githubusercontent.com/assets/1078685/13811844/5a9c0390-eb89-11e5-9044-95e20bca38c9.png)

**Comment by mxl** [comment]
@mikebonnell Tested on Android 4.4.4 - buttons have white background.

**Comment by mikebonnell** [comment]
Can you share your Digits them that you're using? @mxl

**Comment by mxl** [comment]
@mikebonnell 

styles.xml:

    <style name="TwitterDigitsTheme" parent="Theme.AppCompat.Light.DarkActionBar">
        <item name="colorPrimary">@color/primary</item>
        <item name="colorPrimaryDark">@color/primaryDark</item>
        <item name="colorAccent">@color/primary</item>
    </style>

colors.xml:

    <color name="primary">@color/red</color>
    <color name="primaryDark">@color/red700</color>
    <color name="red">#F44336</color>
    <color name="red700">#D32F2F</color>

**Comment by mikebonnell** [comment]
Hey @mxl, 

Sorry for not keeping you updated, but if you update to the latest version of the SDK this should be all set.

**Comment by mxl** [comment]
@mikebonnell Thanks! It looks good now. 
Only missing vertical center alignment of timeout counter makes it slightly imperfect :)

![screen_shot_2016-08-10_at_0_32_14] (https://cloud.githubusercontent.com/assets/1078685/17534488/736510e0-5e9a-11e6-8dc3-2402b8666b90.png)
