### ISSUE TITLE
[1.10.0] Failed to collect an email

### ISSUE THREAD

**Issue by njovy** [twitter/digits-android#55]
Digits failed to collect an email.
HTTP Error: method POST must have a request body., API Error: 0, User Message: Try Again is printed in logcat.
I'm using digits 1.10.0 with okhttp 2.7.5 and okhttp-urlconnection 2.7.5.

**Comment by mikebonnell** [comment]
@njovy It's not clear to me what you're reporting the issue as. Can you please post more details on Twittercommunity.com/c/fabric as this doesn't appear to be a bug with the SDK but with a particular user's email address that you weren't able to capture.

**Comment by njovy** [comment]
@mikebonnell I am pretty sure that this is a bug with the SDK as this error message comes from OkHTTP. OkHTTP doesn't allow to post a request with an empty body. Digits 1.1.0 doesn't work ```withEmailCollection()``` set.

**Comment by efrohnhoefer** [comment]
Likely related to https://github.com/twitter/digits-android/issues/4 or https://github.com/twitter/twitter-kit-android/issues/32. We will investigate.

**Comment by ashwinraghav** [comment]
Fixed in digits 1.10.2
