### ISSUE TITLE
Invalid partner key

### ISSUE THREAD

**Issue by andreshash** [twitter/digits-android#58]
hi, I need help.
I run application demo  digits-android and return in custom phone login that  java.lang.IllegalArgumentException: Invalid partner key

on BuildConfig.java 

PARTNER_KEY = "null"

**Comment by OryschakTwitter** [comment]
Hey! Our custom UI program is currently in closed beta. Please message me @chrisoryschak if you'd like to discuss being part of the beta. Thanks!

**Comment by SylviaDroid** [comment]
Hello,

I am interested about being part of your beta and get a valid Partner Key and I obviously can't contact you directly on GitHub as private messaging seems to be unavailable.

How can I contact you other way?
Thank you !

**Comment by lopezzbelgium** [comment]
I'm also interested, is there a way to test this in an application we are currently developing?
Thanks in advance.
