### ISSUE TITLE
Automatically continue on receiving confirmation code from server 

### ISSUE THREAD

**Issue by YashalShakti** [twitter/digits-android#59]
It would make the user experience a lot more seamless if, on receiving the confirmation code from the server; there was no need to press the _continue_ button.

I understand it could be due to the TOS, which can be tied to "_Send confirmation code_" where the Digits TOS are accepted.

**Comment by efrohnhoefer** [comment]
Thanks for the feedback. You are correct, the user needs to click continue to accept the TOS.
