### ISSUE TITLE
Digits.authenticate : Callback not called.

### ISSUE THREAD

**Issue by pecheriere** [twitter/digits-android#6]
Hi,

I'm trying to use the method Digits.Authenticate because I don't need the custom button. The auth process is working but at the end the AuthCallback is never called (success or failure). If I relaunch the app (without erasing cache), the callback is called (but no Digits activity is launched, informations are read from cache I guess). I trick by doing a performClick on an 'gone' button, but it's not really clean.

May be related to issue https://github.com/twitter/digits-android/issues/5 

I use Digits 1.6.1, installed with the Fabric plugin. Tested on Note 3 with android 5.

**Comment by pecheriere** [comment]
When I use the 1.5.0 version its working as expected.

**Comment by rallat** [comment]
Thanks @pecheriere I will check it out. Have you checked "don't keep activities" inside developer options?

**Comment by pecheriere** [comment]
@rallat no, it's not checked.

**Comment by dustedrob** [comment]
Just ran into this problem as well with 1.6.1. Reverting back to 1.5 fixes it.

**Comment by dustedrob** [comment]
Has this one been solved with the latest version?

**Comment by rallat** [comment]
In version 1.6.0 Digits changed the reference to the AuthCallback implementation passed in the Digits#authenticate call.
Now Digits holds a weak reference (to avoid a memory leak), that means that unless you hold a strong reference, that AuthCallback will be garbage collected and the result of the flow will be never propagated.
You can try to create that AuthCallback on the Application context and that should work.
Thanks

**Comment by rallat** [comment]
I updated the docs to clarify this internal behavior. Please, check it out: http://docs.fabric.io/android/digits/digits.html#set-up-digitsauthbutton

**Comment by dustedrob** [comment]
I just tried putting the AuthCallback in the app context as the new documentation indicates but now the app freezes as soon as i press the Sign In button. I'm using the latest 1.6.2 version. What might be causing it?

**Comment by rallat** [comment]
Can you share your AuthCallback implementation and the piece of code where you start the AuthCallback?
Thanks @dustedrob

**Comment by sudipta-som** [comment]
Creating AuthCallback in Application context is working fine.
Implementation is given here.
https://docs.fabric.io/android/digits/digits.html

**Comment by dudhatparesh** [comment]
Same issue is happening in version 1.8.0
I set authCallback in MainApplication class. still its not getting called.
i used code snipped from following url.
https://docs.fabric.io/android/digits/digits.html

**Comment by oradkovsky** [comment]
Is there any alternative to creating callback in Application context?

**Comment by mxl** [comment]
@rallat What do you mean by "don't keep activities" option? Where is it located?

**Comment by coralinejones1985** [comment]
I have the same issue in 1.9.4.

**Comment by sureshvaavel** [comment]
I have the same issue with digits:1.11.1

**Comment by bnvinay92** [comment]
AuthCallback does not get called when you call Digits.authenticate() the first time, but get's called thereafter. This is on 2.0.1.

**Comment by sysint64** [comment]
read this comment: https://github.com/twitter/digits-android/issues/6#issuecomment-122279222
just make in your Activity, Controller or other class make additional variable e.g.: AuthCallback digitsAuthCallback;
and define this variable in counstructor or onCreate event.
This is working for me.
