### ISSUE TITLE
Custom theme not working on Kitkat

### ISSUE THREAD

**Issue by madwed** [twitter/digits-android#60]
Hello,

I'm using a custom theme that is working perfectly on `Android 5.0+`. It does not work for KitKat and below.  Any clue as to how I can get this working?

Here's my style code
```
<style name="CustomDigitsTheme" parent="android:Theme.Holo.Light">
      <item name="android:textColorPrimary">@android:color/black</item>
      <item name="android:textColorSecondary">@android:color/darker_gray</item>
      <item name="android:windowBackground">@android:color/white</item>
      <item name="android:textColorLink">#35a6d2</item>
      <item name="android:colorAccent">#35a6d2</item>
</style>
```
Thanks!

**Comment by efrohnhoefer** [comment]
Some code and/or error messages would help...

**Comment by madwed** [comment]
Added my style code.  Haven't seen any errors in RunTime, but I'll crawl over build and the general log.

**Comment by efrohnhoefer** [comment]
`android:colorAccent` attribute wasn't added until Android 5.0+ (API 21+). You should use `dgts__accentColor` attribute to set accent for Digits.

**Comment by efrohnhoefer** [comment]
Some example can be found here: https://docs.fabric.io/android/digits/theming.html#examples

**Comment by madwed** [comment]
Great, that was the issue.  Thanks!
