### ISSUE TITLE
An app name has non ASCII characters throws an exception.

### ISSUE THREAD

**Issue by njovy** [twitter/digits-android#66]
```
HTTP Error: Unexpected char 0xb79c at 20 in header value: Digits/1.10.3.111 ( 테스트; Android 6.0.1), API Error: 0, User Message: 다시 시도
```
I looked up the Digits source code and it builds its user agent with a current app name from a package manager. The above is the error I'm getting if an app name contains a non ASCII character. [JakeWharton's comment](https://github.com/square/retrofit/issues/1178#issuecomment-146425484) mentioned that OkHttp validates header values so using a current app name in user agent needs to be changed to support non-english apps.

**Comment by efrohnhoefer** [comment]
@njovy Thank you for the issue report. This is a known issue. I believe this will be updated in the next release.

**Comment by efrohnhoefer** [comment]
This issue has been resolved: https://github.com/twitter/digits-android/commit/0600a305efbec8ab46a6578145e39cd7f981a295

Please update to latest version.
