### ISSUE TITLE
HTTP Error: 403 Forbidden, API Error: 306

### ISSUE THREAD

**Issue by goznauk** [twitter/digits-android#73]
I've got the error message via developing a new application, but I can't figure out what's wrong with my code. Does anyone have idea about this error message?

```
07-17 08:34:17.236 E/Digits: HTTP Error: 403 Forbidden, API Error: 306, User Message: Try Again
```

**Comment by efrohnhoefer** [comment]
306: "To protect our users from spam and other malicious activity, this account is temporarily blocked from acquiring an access token for this client application." If you think this is in error you should contact support@fabric.io

**Comment by goznauk** [comment]
Thanks! Maybe I've requested too much when i'm testing my feature. Thank you for your kind reply 👍
